/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.component.HoaDon;

import BUS.ChiTietHoaDonBUS;
import BUS.HoaDonBUS;
import BUS.KhachhangBUS;
import BUS.NhanvienBUS;
import BUS.SanphamBUS;
import DTO.ChiTietHoaDonDTO;
import DTO.HoaDonDTO;
import DTO.KhachhangDTO;
import DTO.NhanvienDTO;
import DTO.SanphamDTO;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mrben
 */
public class ChiTietHoaDon extends javax.swing.JPanel {

    private HoaDonBUS hoaDonBUS;
    private ChiTietHoaDonBUS chiTietHoaDonBUS;
    private NhanvienBUS nhanvienBUS;
    private KhachhangBUS khachhangBUS;
    private SanphamBUS sanphamBUS;
    private DecimalFormat decimalFormat;
    private SimpleDateFormat dateFormat;
    private String currentMaHD;

    /**
     * Creates new form ChiTietHoaDon
     */
    public ChiTietHoaDon() {
        initComponents();

        // Initialize BUS objects
        hoaDonBUS = new HoaDonBUS();
        chiTietHoaDonBUS = new ChiTietHoaDonBUS();
        nhanvienBUS = new NhanvienBUS();
        khachhangBUS = new KhachhangBUS();
        sanphamBUS = new SanphamBUS();

        // Initialize formatters
        decimalFormat = new DecimalFormat("#,###");
        dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    }

    /**
     * Constructor that loads an invoice by ID
     * 
     * @param maHD The invoice ID to load
     */
    public ChiTietHoaDon(String maHD) {
        this();
        loadHoaDonDetails(maHD);
    }

    /**
     * Loads and displays invoice details
     * 
     * @param maHD The invoice ID to load
     */
    public final void loadHoaDonDetails(String maHD) {
        try {
            // Get invoice information
            HoaDonDTO hoaDon = hoaDonBUS.getHoaDonById(maHD);

            if (hoaDon == null) {
                JOptionPane.showMessageDialog(this,
                        "Không tìm thấy hóa đơn với mã: " + maHD,
                        "Thông báo",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Store current invoice ID
            currentMaHD = maHD;

            // Get employee and customer information
            NhanvienDTO nhanVien = nhanvienBUS.getNhanvienByMaNV(hoaDon.getMa_nhan_vien());
            KhachhangDTO khachHang = khachhangBUS.getKhachhangByMaKH(hoaDon.getMa_khach_hang());

            // Display invoice information
            lblMaHoaDonValue.setText(maHD);
            lblNhanVienValue.setText(hoaDon.getMa_nhan_vien() + " - " +
                    (nhanVien != null ? nhanVien.getHo_ten() : "Unknown"));
            lblKhachHangValue.setText(hoaDon.getMa_khach_hang() + " - " +
                    (khachHang != null ? khachHang.getHo_ten() : "Unknown"));
            lblNgayLapValue.setText(dateFormat.format(hoaDon.getNgay_lap()));
            lblTongTienValue.setText(decimalFormat.format(hoaDon.getTong_tien()) + " VNĐ");

            // Get invoice details
            ArrayList<ChiTietHoaDonDTO> chiTietList = chiTietHoaDonBUS.getChiTietHoaDonByMaHD(maHD);

            // Display invoice details in table
            DefaultTableModel model = (DefaultTableModel) tableSanPham.getModel();
            model.setRowCount(0);

            int stt = 1;
            for (ChiTietHoaDonDTO chiTiet : chiTietList) {
                SanphamDTO sanPham = sanphamBUS.getSanphamById(chiTiet.getMa_sp());
                String tenSP = sanPham != null ? sanPham.getTenSP() : "Unknown";

                // Add raw numeric values to the table, not formatted strings
                model.addRow(new Object[] {
                        stt++,
                        chiTiet.getMa_sp(),
                        tenSP,
                        chiTiet.getSo_luong(),
                        chiTiet.getDon_gia(), // Use raw numeric value
                        chiTiet.getThanh_tien() // Use raw numeric value
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Lỗi khi tải thông tin hóa đơn: " + e.getMessage(),
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        lblMaHoaDon = new javax.swing.JLabel();
        lblMaHoaDonValue = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        lblNhanVienValue = new javax.swing.JLabel();
        lblKhachHang = new javax.swing.JLabel();
        lblKhachHangValue = new javax.swing.JLabel();
        lblNgayLap = new javax.swing.JLabel();
        lblNgayLapValue = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        lblTongTienValue = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSanPham = new javax.swing.JTable();
        btnInHoaDon = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        headerPanel.setBackground(new java.awt.Color(8, 122, 230));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("CHI TIẾT HÓA ĐƠN");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
                headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));
        headerPanelLayout.setVerticalGroup(
                headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                .addContainerGap()));

        lblMaHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaHoaDon.setText("Mã hóa đơn:");

        lblMaHoaDonValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaHoaDonValue.setText("HD001");

        lblNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNhanVien.setText("Nhân viên:");

        lblNhanVienValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNhanVienValue.setText("NV001 - Nguyễn Văn A");

        lblKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblKhachHang.setText("Khách hàng:");

        lblKhachHangValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblKhachHangValue.setText("KH001 - Trần Thị B");

        lblNgayLap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNgayLap.setText("Ngày lập:");

        lblNgayLapValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNgayLapValue.setText("01/01/2023");

        lblTongTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTongTien.setText("Tổng tiền:");

        lblTongTienValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongTienValue.setForeground(new java.awt.Color(204, 0, 0));
        lblTongTienValue.setText("1,000,000 VNĐ");

        tableSanPham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableSanPham.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "STT", "Mã SP", "Tên sản phẩm", "Số lượng", "Đơn giá", "Thành tiền"
                }) {
            Class[] types = new Class[] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class,
                    java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tableSanPham.setRowHeight(25);
        tableSanPham.setSelectionBackground(new java.awt.Color(8, 122, 230));
        tableSanPham.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableSanPham);

        btnInHoaDon.setBackground(new java.awt.Color(8, 122, 230));
        btnInHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnInHoaDon.setText("In");
        btnInHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInHoaDonActionPerformed(evt);
            }
        });

        btnDong.setBackground(new java.awt.Color(8, 122, 230));
        btnDong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDong.setForeground(new java.awt.Color(255, 255, 255));
        btnDong.setText("Đóng");
        btnDong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 743,
                                                Short.MAX_VALUE)
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addGroup(mainPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                                .addComponent(lblMaHoaDon)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(lblMaHoaDonValue,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 250,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                                .addGroup(mainPanelLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lblNhanVien)
                                                                        .addComponent(lblKhachHang)
                                                                        .addComponent(lblNgayLap)
                                                                        .addComponent(lblTongTien))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(mainPanelLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(lblNhanVienValue,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                250, Short.MAX_VALUE)
                                                                        .addComponent(lblKhachHangValue,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(lblNgayLapValue,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(lblTongTienValue,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                mainPanelLayout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(btnInHoaDon,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap()));
        mainPanelLayout.setVerticalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(
                                        mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lblMaHoaDon)
                                                .addComponent(lblMaHoaDonValue))
                                .addGap(18, 18, 18)
                                .addGroup(
                                        mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lblNhanVien)
                                                .addComponent(lblNhanVienValue))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(
                                        mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lblKhachHang)
                                                .addComponent(lblKhachHangValue))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(
                                        mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lblNgayLap)
                                                .addComponent(lblNgayLapValue))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(
                                        mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lblTongTien)
                                                .addComponent(lblTongTienValue))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(
                                        mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btnInHoaDon)
                                                .addComponent(btnDong))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    private void btnInHoaDonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnInHoaDonActionPerformed
        if (currentMaHD == null || currentMaHD.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Không có hóa đơn để in",
                    "Thông báo",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Here you would implement the printing functionality
        // For now, just show a message
        JOptionPane.showMessageDialog(this,
                "Đang in hóa đơn: " + currentMaHD,
                "Thông báo",
                JOptionPane.INFORMATION_MESSAGE);
    }// GEN-LAST:event_btnInHoaDonActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDongActionPerformed
        // Close the panel or dialog
        if (this.getParent() instanceof javax.swing.JDialog) {
            ((javax.swing.JDialog) this.getParent()).dispose();
        }
    }// GEN-LAST:event_btnDongActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnInHoaDon;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKhachHang;
    private javax.swing.JLabel lblKhachHangValue;
    private javax.swing.JLabel lblMaHoaDon;
    private javax.swing.JLabel lblMaHoaDonValue;
    private javax.swing.JLabel lblNgayLap;
    private javax.swing.JLabel lblNgayLapValue;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblNhanVienValue;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel lblTongTienValue;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable tableSanPham;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
