/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import GUI.event.EventMenuSelected;
import GUI.form.Form_Home;
import GUI.form.Form_Sanpham;
import GUI.form.Form_Loaisp;
import GUI.form.Form_Nhacungcap;
import GUI.form.Form_Phieunhap;
import GUI.form.Form_Khachhang;
import GUI.form.Form_Nhanvien;
import GUI.form.Form_HoaDon;
import GUI.form.Form_Khuyenmai;
import GUI.form.Form_ThongKe;

import java.awt.Color;
import javax.swing.JComponent;

/**
 *
 * @author mrben
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    private Form_Home home;
    private Form_Sanpham sanpham;
    private Form_Loaisp loaisp;
    private Form_Phieunhap phieunhap;
    private Form_Nhacungcap nhacungcap;
    private Form_Khachhang khachhang;
    private Form_Nhanvien nhanvien;
    private Form_HoaDon hoadon;
    private Form_ThongKe thongke;
    private Form_Khuyenmai khuyenmai;

  
    public MainForm() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        
        home = new Form_Home();
        sanpham = new Form_Sanpham();
        loaisp = new Form_Loaisp();
        phieunhap = new Form_Phieunhap();
        nhacungcap = new Form_Nhacungcap();
        khachhang = new Form_Khachhang();
        nhanvien = new Form_Nhanvien();
        hoadon = new Form_HoaDon();
        thongke = new Form_ThongKe();
        khuyenmai = new Form_Khuyenmai();
        
       
        menu.initMoving(MainForm.this);
        menu.addEventMenuSelected(new EventMenuSelected(){
            @Override
            public void selected(int index) {
                if(index == 0) {
                    setForm(home);
                } else if (index == 1) {
                    setForm(sanpham);
                } else if (index == 2) {
                    setForm(loaisp);
                } else if (index == 3) {
                    setForm(phieunhap);
                } else if (index == 4) {
                    setForm(nhacungcap);
                } else if (index == 5) {
                    setForm(khachhang);
                } else if (index == 6) {
                    setForm(nhanvien);
                } else if (index == 7) {
                    setForm(hoadon);
                } else if (index == 8) {
                    setForm(thongke);
                } else if (index == 9) {
                    setForm(khuyenmai);
                } 
            }
        });
        setForm(new Form_Home());
        this.setVisible(true); 
    }
    
    private void setForm(JComponent com){
        mainPanel.removeAll();
        mainPanel.add(com);
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new GUI.swing.PanelBorder();
        menu = new GUI.component.Menu();
        header1 = new GUI.component.Header();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainPanel.setOpaque(false);
        mainPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header1, javax.swing.GroupLayout.DEFAULT_SIZE, 1084, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.component.Header header1;
    private javax.swing.JPanel mainPanel;
    private GUI.component.Menu menu;
    private GUI.swing.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
