/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.component.SanPham;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import DTO.SanphamDTO;
import DTO.ChiTietSanPhamDTO;
import BUS.SanphamBUS;
import BUS.ChiTietSanPhamBUS;
import BUS.LoaisanphamBUS;
import DTO.LoaisanphamDTO;
import java.math.RoundingMode;
import java.text.DecimalFormat;
/**
 *
 * @author ADMIN
 */
public class InforSanPhamForm extends javax.swing.JFrame {
    SanphamBUS sanPhamBUS;
    ChiTietSanPhamBUS chiTietSanPhamBUS;

    LoaisanphamBUS loaiBUS;
    private ArrayList<LoaisanphamDTO> dsLoai;
    /**
     * Creates new form InforSanPhamForm
     */
    public InforSanPhamForm() {
        initComponents();
        sanPhamBUS = new SanphamBUS();
        chiTietSanPhamBUS = new ChiTietSanPhamBUS();
        loaiBUS = new LoaisanphamBUS();
        
         dsLoai = loaiBUS.getList(); //  Dòng này rất quan trọng

     // Đổ sẵn các loại sản phẩm vào combobox
        if (dsLoai != null) {
            for (LoaisanphamDTO loai : dsLoai) {
               cbLoaiSP.addItem(loai.getTen_loai());
           }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        information_panel = new javax.swing.JPanel();
        txtMaSP = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        txtRAM = new javax.swing.JTextField();
        txtCPU = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        cbLoaiSP = new javax.swing.JComboBox<>();
        txtCard = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        information_panel.setBackground(new java.awt.Color(255, 255, 255));
        information_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHI TIẾT SẢN PHẨM", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        txtMaSP.setBorder(javax.swing.BorderFactory.createTitledBorder("Mã sản phẩm"));
        txtMaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSPActionPerformed(evt);
            }
        });

        txtTenSP.setBorder(javax.swing.BorderFactory.createTitledBorder("Tên sản phẩm"));

        txtRAM.setBorder(javax.swing.BorderFactory.createTitledBorder("RAM"));

        txtCPU.setBorder(javax.swing.BorderFactory.createTitledBorder("CPU"));

        txtGia.setBorder(javax.swing.BorderFactory.createTitledBorder("Giá bán"));
        txtGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaActionPerformed(evt);
            }
        });

        cbLoaiSP.setBorder(javax.swing.BorderFactory.createTitledBorder("Loại sản phẩm"));

        txtCard.setBorder(javax.swing.BorderFactory.createTitledBorder("Card "));

        txtSoLuong.setBorder(javax.swing.BorderFactory.createTitledBorder("Số lượng"));
        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout information_panelLayout = new javax.swing.GroupLayout(information_panel);
        information_panel.setLayout(information_panelLayout);
        information_panelLayout.setHorizontalGroup(
            information_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(information_panelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(information_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCard)
                    .addComponent(txtMaSP)
                    .addComponent(txtTenSP)
                    .addComponent(cbLoaiSP, 0, 250, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(information_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCPU)
                    .addComponent(txtRAM)
                    .addComponent(txtGia)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        information_panelLayout.setVerticalGroup(
            information_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(information_panelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(information_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaSP)
                    .addComponent(txtRAM))
                .addGap(27, 27, 27)
                .addGroup(information_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenSP)
                    .addComponent(txtCPU))
                .addGap(28, 28, 28)
                .addGroup(information_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGia)
                    .addComponent(cbLoaiSP))
                .addGap(35, 35, 35)
                .addGroup(information_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCard, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(information_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(information_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSPActionPerformed

    private void txtGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaActionPerformed

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    public void setDataForView(SanphamDTO sp) {
        if (sp != null) {
            ChiTietSanPhamDTO ctsp = chiTietSanPhamBUS.getCTSPByMaSP(sp.getMa_sp());

            // Thiết lập tất cả các JTextField là không cho chỉnh sửa
            // Đặt các trường chỉ đọc
            JTextField[] fields = { txtMaSP, txtTenSP, txtRAM, txtCPU, txtCard, txtGia, txtSoLuong };
            for (JTextField field : fields) {
                field.setEditable(false);
                field.setBackground(new java.awt.Color(240, 240, 240));
            }
            cbLoaiSP.setEnabled(false);
            
            // Đổ dữ liệu vào các trường
            txtMaSP.setText(sp.getMa_sp());
            txtTenSP.setText(sp.getTenSP());
            txtRAM.setText(ctsp.getRam());
            txtCPU.setText(ctsp.getChip());
            txtCard.setText(ctsp.getCard());
            txtGia.setText(String.valueOf((long) ctsp.getGia_ban()));
            txtSoLuong.setText(String.valueOf(ctsp.getSo_luong_ton()));

            // Set loại sản phẩm
            cbLoaiSP.removeAllItems(); // xóa các item cũ
            dsLoai = loaiBUS.getList();
            for (LoaisanphamDTO loai : dsLoai) {
                cbLoaiSP.addItem(loai.getTen_loai());
                if (loai.getMa_loai().equals(sp.getMa_loai())) {
                    cbLoaiSP.setSelectedItem(loai.getTen_loai());
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InforSanPhamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InforSanPhamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InforSanPhamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InforSanPhamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InforSanPhamForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbLoaiSP;
    private javax.swing.JPanel information_panel;
    private javax.swing.JTextField txtCPU;
    private javax.swing.JTextField txtCard;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtRAM;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    // End of variables declaration//GEN-END:variables
}
